services:
  - type: web
    name: fraud-api
    runtime: python
    region: oregon
    plan: free
    buildCommand: "pip install --upgrade pip && pip install -r requirements-basic.txt"
    startCommand: "python app/main_simple.py"
    envVars:
      - key: PORT
        value: 10000
      - key: HOST
        value: "0.0.0.0"
      - key: ENVIRONMENT
        value: production
      - key: API_VERSION
        value: v2
    healthCheckPath: /health
    
  - type: web
    name: fraud-dashboard
    runtime: python
    region: oregon
    plan: free
    buildCommand: "pip install --upgrade pip && pip install -r requirements-dashboard.txt"
    startCommand: "streamlit run dashboard/app_simple.py --server.port $PORT --server.address 0.0.0.0 --server.headless true"
    envVars:
      - key: PORT
        value: 10000
      - key: API_URL
        value: https://fraud-api.onrender.com
      - key: STREAMLIT_SERVER_HEADLESS
        value: "true"
      - key: STREAMLIT_BROWSER_GATHER_USAGE_STATS
        value: "false"
